export const THEMES = {
  DARK: 'DARK',
  LIGHT: 'LIGHT',
  AUTOMATIC: 'AUTOMATIC'
};

export const EVENTS = {
  THEME_CHANGED: 'THEME_CHANGED'
};

export const STORAGE_KEYS = {
  SELECTED_THEME_TYPE: 'SELECTED_THEME_TYPE',
  SELECTED_THEME: 'SELECTED_THEME'
};
